### ISSUE TITLE
Тестирование сборки 0.0.7

### ISSUE THREAD

**Issue by MantisReligiosa** [MantisReligiosa/Display-control#111]

**Comment by MantisReligiosa** [comment]
Билд 98: https://dev.azure.com/mantis-religiosa/f885b45e-6407-4363-a4b4-3c2f41dda368/_apis/build/builds/98/artifacts?artifactName=Installer&fileId=E6C64E3A7593D9A470848F4880A965161677D1DD3369A045366E483700A67D6102&fileName=Display_control_v0.0.7_build_98.msi&api-version=5.0-preview.3

На тест не ставил, т.к. нет доступа

**Comment by Kim134** [comment]
1. При наполнении контента во втором сценарии появляется ошибка при которой невозможно корректировать местоположение блоков  и вносить другие изменения.
![image](https://app.gitkraken.com/api/glo/boards/5c6c369bcd1b7702438eebfe/attachments/5d4aad2a11fc31000f960dc4)

**Comment by Kim134** [comment]
в консоли ошибок нет! При ручном обновлении стр. - появляются дополнительно два сценария, которые я удалял в самом начале.

**Comment by Kim134** [comment]
2. При удалении блока ТЕКСТ появилась ошибка в консоле:
vendor?r=88ACF49EC3F815E5BC281F2D42FC4601:1 Uncaught TypeError: Cannot read property 'state' of undefined

**Comment by Kim134** [comment]
3. При добавлении текстового блока в сценарий с таблицей - ошибка:
![image](https://app.gitkraken.com/api/glo/boards/5c6c369bcd1b7702438eebfe/attachments/5d4aaf5e647fd9000f1c7c5f)

**Comment by Kim134** [comment]
4. При изменении шрифта в таблице и нажатии - ок:
![image](https://app.gitkraken.com/api/glo/boards/5c6c369bcd1b7702438eebfe/attachments/5d4ab1482ba611000ff29c1d)

**Comment by Kim134** [comment]
5. при удалении одного из представлений - ошибка сохранения блока.

**Comment by MantisReligiosa** [comment]
Завел задачу 113

**Comment by MantisReligiosa** [comment]
Билд 116 установлен на тест. Ссылка на билд: https://dev.azure.com/mantis-religiosa/f885b45e-6407-4363-a4b4-3c2f41dda368/_apis/build/builds/116/artifacts?artifactName=Installer&fileId=4A020FBE1124F8CD7EC251D1AA529ED8E7AEDB02980005F9DDBC3775A59DF88E02&fileName=Display_control_v0.0.7_build_116.msi&api-version=5.0-preview.3

**Comment by Kim134** [comment]
6. Интервал. Добавить режим авто и увеличить ручной выбор до 5.
Все таки "иногда" не работает авто! А если править в ручную не хватает "бо`льшего" шага.

**Comment by Kim134** [comment]
7. При перемещении большого блока - СЦЕНАРИЙ, возникает ошибка после которой идут следом другие. Это так же распространяется на независимый блок вне сценария - например ТЕКСТ (если сделать заголовок не в сценарии).

**Comment by Kim134** [comment]
8. Возможна ли корректировка таблицы, а именно размера строк и колонок в браузере?

**Comment by Kim134** [comment]
9. Последние две недели идут ТЗ с бегущей строкой. Сложно добавить такой эффект для блока текста?

**Comment by Kim134** [comment]
10. CSV файл, добавить кодировку win
![image](https://app.gitkraken.com/api/glo/boards/5c6c369bcd1b7702438eebfe/attachments/5d57c31ec3bf7c0015ad064b)

**Comment by Kim134** [comment]
11. Все таки нужно добавить кнопку "обновить корректировки на табло". Не удобно после каждого исправления или смены контента нажимать пуск и стоп.

**Comment by Kim134** [comment]
12. При добавлении еще одного сценария, даже после выключения и влючения ПО - ошибка.
![image](https://app.gitkraken.com/api/glo/boards/5c6c369bcd1b7702438eebfe/attachments/5d5932c1829ec4000f6d6fb2)

**Comment by Kim134** [comment]
13. При добавлении картинки в представление - ошибка
![image](https://app.gitkraken.com/api/glo/boards/5c6c369bcd1b7702438eebfe/attachments/5d62615a6523b7000f202c3a)

**Comment by Kim134** [comment]
А после перезагрузки ПО, исчезло представление в который добавлял картинку ))

**Comment by Kim134** [comment]
14. Не могу добавить блок ДАТА/ВРЕМЯ

**Comment by Kim134** [comment]
По часам, сегодня смог добавить блок, время отображается. Но иероглифы в основном меню, при выборе формата отображения.

**Comment by MantisReligiosa** [comment]
На это есть задача 89

**Comment by MantisReligiosa** [comment]
Билд 118 установлен на тест. Ссылка на билд: https://dev.azure.com/mantis-religiosa/f885b45e-6407-4363-a4b4-3c2f41dda368/_apis/build/builds/118/artifacts?artifactName=Installer&fileId=66339846587CA1D519F9643DF7F7B0366BF574E2759F8F62818E1B443BE5733302&fileName=Display_control_v0.0.7_build_118.msi&api-version=5.0-preview.3

**Comment by Kim134** [comment]
принято!

**Comment by Kim134** [comment]
Баг со СЦЕНАРИЯМИ
При обновлении стр.  появляется лишний сценарий и при выделении в древе любого из двух - выделяются оба
![image](https://app.gitkraken.com/api/glo/boards/5c6c369bcd1b7702438eebfe/attachments/5d76628cd69294000f01fe55)

**Comment by Kim134** [comment]
Блок дата/время
Появилась ошибка - не могу добавить данный блок
![image](https://app.gitkraken.com/api/glo/boards/5c6c369bcd1b7702438eebfe/attachments/5d7662f3d69294000f01fe65)

**Comment by Kim134** [comment]
не могу передвинуть блоки...
![image](https://app.gitkraken.com/api/glo/boards/5c6c369bcd1b7702438eebfe/attachments/5d766575e6bd4e000ffc28ec)

**Comment by MantisReligiosa** [comment]
Опять базу нужно почистить. Нужно скорее приступать к автотестам, чтобы все эти баги воспроизвести и убрать. Переходим к версии 0.0.8?

**Comment by Kim134** [comment]
Алексей, а как заказчик будет базу чистить? это же целая ситуация....
Да, переходим на 0,0,8

**Comment by MantisReligiosa** [comment]
Если мы сейчас на 0.0.8 тестами эти баги отловим и починим, то не придется больше чистить базу
