### ISSUE TITLE
автозагрузка данных, CSV

### ISSUE THREAD

**Issue by Kim134** [MantisReligiosa/Display-control#24]
ПО/сервер должен уметь забирать файлы и отображать их автоматически. Например - выбираем автозагрузка в указанном блоке, указываем путь и все. Последний по дате и времени файл забирается сервером и табло обновляется (здесь бы я еще добавил возможность редактировать период обновления/забора csv файла).

**Comment by MantisReligiosa** [comment]
Уже заведена задача #9
Закрываю как дубликат
