### ISSUE TITLE
Баг. Появление ромбиков вместо текста и символов.

### ISSUE THREAD

**Issue by Kim134** [MantisReligiosa/Display-control#35]

**Comment by Kim134** [comment]
При создании таблицы, действия: таблица> свойства> импорт из файла>выбираем csv файл -> отображаются ромбики вместо символов 
![image](https://app.gitkraken.com/api/glo/boards/5c6c369bcd1b7702438eebfe/attachments/5c8dee9ac68810000ff734ee)

**Comment by MantisReligiosa** [comment]
Уже заведена задача #10. Закрываю как дубликат
