### ISSUE TITLE
!Визуализация! увеличение шрифта!

### ISSUE THREAD

**Issue by Kim134** [MantisReligiosa/Display-control#37]

**Comment by Kim134** [comment]
Алексей, при увеличении шрифта, естественно уменьшается количество строк и столбцов для отображения. Вопрос в следующем: какой алгоритм показа? А именно если у нас не помещаются строки они будут показаны дополнительно следующим экраном или данные "съедаются"?

**Comment by MantisReligiosa** [comment]
Александр, сейчас данные "съедаются"

**Comment by Kim134** [comment]
Нужно сразу решить алгоритм воспроизведения, на потом не откладывать.
