### ISSUE TITLE
!Визуализация! смена экранов!

### ISSUE THREAD

**Issue by Kim134** [MantisReligiosa/Display-control#38]

**Comment by Kim134** [comment]
Алексей, решил отдельной темой завести вопрос о смене экрана, для показа непоместившихся строк. Веди если строки расписания не поместились сразу, необходимо показать последние с тем же заголовком. Каков алгоритм формирования "допоказа"? Мы должны сразу формировать контент - с учетом размеров визуализации и т.д. Или ПО покажет само таблицу, а непоместившиеся данные "допокажет" с тем же заголовком?

**Comment by MantisReligiosa** [comment]
Александр, моя позиция не поненялась - я предлагаю жёстко обрезать таблицы. И не делать допоказ, т.к. это по большому счёту неуправляемый процесс. С появлением метаблоков мы сможем создавать кадры с отдельными таблицыми. Так и будет реализовываться показ большого колическва информации. Предлагаю задачи #38 и #37 закрывть

**Comment by Kim134** [comment]
хорошо согласен, забыл про метаблоки.
