### ISSUE TITLE
баг. Пр пуске ПО

### ISSUE THREAD

**Issue by Kim134** [MantisReligiosa/Display-control#39]

**Comment by Kim134** [comment]
при пуску ПО заливается полностью полоска с лева. На остальном экране ПО не отображается. Видимо это ошибка связана с некорректным отображением (не по размеру) самого экрана в веб интерфейса. 
![image](https://app.gitkraken.com/api/glo/boards/5c6c369bcd1b7702438eebfe/attachments/5c8df4cde942df000f934257)

**Comment by Kim134** [comment]
Отловил! :)) Поменял на книжную ориентацию ОТОБРАЖЕНИЕ запустилось на весь экран, сначала перевернутое, после само перешло в режим альбомной.

**Comment by MantisReligiosa** [comment]
Закрываю как дубликат задачи #36
