### ISSUE TITLE
формат импортируемых данных (таблица).

### ISSUE THREAD

**Issue by Kim134** [MantisReligiosa/Display-control#40]

**Comment by Kim134** [comment]
Алексей, по поводу формата - неудобно делать в utf -8! Приходится заливать и конвертировать через googl документ или путем пересохранения файлов. Нужна поддержка загружаемых файлов не только в utf-8. Идеально если через ms office можно было сохранить в один клик. И еще, сегодня напишу/спрошу партнерам, в каком формате csv сохраняет ПО РЖД.

**Comment by MantisReligiosa** [comment]
Уже заведена фича #10. При необходимости повышайте ей приоритет. Эту карточку предлагаю закрыть
