### ISSUE TITLE
реализовать кнопку - привязать к сетке

### ISSUE THREAD

**Issue by Kim134** [MantisReligiosa/Display-control#44]

**Comment by MantisReligiosa** [comment]
Какой функционал будет у этой кнопки?

**Comment by Kim134** [comment]
Если честно, я взял этот пункт из инструкции, чтоб не забыли. Функционал - тобой придуман.

**Comment by Kim134** [comment]
ОПИСАНИЕ: "Для облегчения выравнивания блоков предусмотрена функция привязка к сетке. Настройка сетки выполняется в группе “Расположение и слой” вкладки “Видеостена”.  После включения привязки значения размеров блока и его координаты будут кратны шагу сетки. Например, если выбран шаг сетки 25, то возможны следующие значения: 0, 25, 50, 75, 100 и т.д.
"

**Comment by MantisReligiosa** [comment]
Реализовано. За это отвечает флажок "Привязать к сетке"
