### ISSUE TITLE
не видны границы уже добавленных зон

### ISSUE THREAD

**Issue by Kim134** [MantisReligiosa/Display-control#51]

**Comment by Kim134** [comment]
![image](https://app.gitkraken.com/api/glo/boards/5c6c369bcd1b7702438eebfe/attachments/5cbdd7c3630d92000feb32a5)

**Comment by Kim134** [comment]
для эффективного наполнения данными и избежания ошибок, нужно выделить "черным" цветом границы ранее созданных и неактивных блоков.

**Comment by MantisReligiosa** [comment]
Уже заведена карточка #43. Эту предлагаю закрыть

**Comment by Kim134** [comment]
что-то не увидел. закрываем
