### ISSUE TITLE
copy past

### ISSUE THREAD

**Issue by Kim134** [MantisReligiosa/Display-control#52]

**Comment by Kim134** [comment]
Если скопировать блок и потом вставить, а затем попытаться сместить вставленный блок - он перемещается только в зоне скопированного блока.

**Comment by Kim134** [comment]
![image](https://app.gitkraken.com/api/glo/boards/5c6c369bcd1b7702438eebfe/attachments/5cbdd8d9630d92000feb32cd)

**Comment by MantisReligiosa** [comment]
Копируемый блок находится в метаблоке. Поэтому и вставляемый блок будет в метаблоке и за его пределы не выйдет. Не баг, а фича. Предлагаю закрыть карточку

**Comment by Kim134** [comment]
Алексей, давай определяться. Метаблок - это разные программы в одних границах или разные программы в одном сценарии, но могут они отображаться в любом месте экрана_ов?

**Comment by MantisReligiosa** [comment]
Сейчас метаблок - это некоторая область с четкими границами. Метаблок может иметь несколько кадров, а каждый кадр содержит один или более простых блоков
