### ISSUE TITLE
Вопрос по сценариям воспроизведения

### ISSUE THREAD

**Issue by Kim134** [MantisReligiosa/Display-control#57]

**Comment by Kim134** [comment]
Алексей, я все таки хочу решить по сценарию воспроизведения:
1. Например создаем СЦЕНАРИЙ №1 - в него входят метаблоки, таблицы (с авто обновлением или без), текст он же заголовок он же статистическое изображение, картинка/фото или слайд  и т.д. Сценарий проигрывается на всех экранах (от 1 до ....мониторах). В сценарии задаем время показа или в каждом блоке? Или в метаблоке? Где есть данная функция?
2. Самое большое время думаю будет у таблиц и информационных текстовых блоков, которые могут состоять из нескольких страниц и сменять друг друга по очереди. ВОПРОС - остальные блоки или метаблоки будут на повторе, пока проигрывается самый "долгий" блок? Каждая страница у таблицы с заданным показом в секундах, иначе не успеют прочитать.
3. Проигрывается СЦЕНАРИЙ №1, далее СЦЕНАРИЙ №2 и т.д.?

**Comment by MantisReligiosa** [comment]
Александр, мне уже начинает сильно мешать наша неопределённость. Пишу ещё и здесь тот же коммент, что и в задаче #52. Нам категорически срочно нужно определиться с терминами. Какая смыслоая нагрузка у понятия СЦЕНАРИЙ?

**Comment by Kim134** [comment]
Какая неопределенность? Я написал как я вижу/видел создание контента для визуализации на экранах. Вот жду твоего видения...

**Comment by MantisReligiosa** [comment]
У меня не получается увязать в одну концепцию метаблоки и сценарии, потому что они в моём понимании служат для одного и того же - показывать сменяющиеся блоки.

**Comment by MantisReligiosa** [comment]
Я предлагаю сейчас всё же добить вопрос с разворачиванием тестовог стенда, тогда думаю вживую можно будет проработать этот вопрос
