### ISSUE TITLE
долгий отклик в свойствах

### ISSUE THREAD

**Issue by Kim134** [MantisReligiosa/Display-control#66]

**Comment by Kim134** [comment]
Очень долгий отклик в свойствах (например если изменять цвет фона или размер шрифта).

**Comment by MantisReligiosa** [comment]
При первом раскрытии списка шрифтов тормоза не убрать - происходит загрузка всех шрифтов ОС. В последующие разы список раскрывается очень быстро.

Или имеется в виду, что после нажатия кнопки ОК долго отрабатывает?

**Comment by Kim134** [comment]
именно при первом раскрытии, любого блока. Даже если мы сначала открыли Текст, после открываем другой - все равно подгружается долго.

**Comment by Kim134** [comment]
Алексей, здесь еще наложилось неоткрытие меню цвета и фона. Так что - РЕШЕНО.
по цвету и фону задача
