### ISSUE TITLE
Удаление в  Метаблоке

### ISSUE THREAD

**Issue by Kim134** [MantisReligiosa/Display-control#71]

**Comment by Kim134** [comment]
Если выделить кадр 1, в метаблоке и нажать УДАЛИТЬ – удалиться весь метаблок! не Удобно. А дальнейшие пользователи так и будут делать!

**Comment by MantisReligiosa** [comment]
Кадры удаляются и добавляются в свойствах метаблока. Иначе как различить удаление кадра и всего метаблока?

**Comment by Kim134** [comment]
Здесь нужен общий подход. Что выделяем - то и удаляем

**Comment by MantisReligiosa** [comment]
Я предлагаю всё же оставить как есть. Потому что во-первых, на рабочей области непонятно, что выделен именно кадр, а не весь метаблок. Получается, что при щелчке по метаблоку на рабочей области выделится (и удалится)  весь метаблок, а при щелчке по кадру в дереве выделится и удалится кадр. При том, что рамочка на рабочей области будет выглядеть абсолютно одинаково что в первом, что во втором случае. И это может сильно запутать.
Во вторых, в свойствах метаблока будут собраны все функции по управлению кадрами: добавить новый, изменить порядок, указать время захвата, задать расписание. Логично, что и удаление должно быть здесь. 
И в-третьих, кадр - это в некотором роде свойство метаблока, его часть. А кнопка служит для удаления именно блоков.
