### ISSUE TITLE
Более одного монитора!

### ISSUE THREAD

**Issue by Kim134** [MantisReligiosa/Display-control#72]

**Comment by Kim134** [comment]
Подключил к Ноуту второй монитор. ПО не отображает в браузере. При пуске, то что не поместилось (маленькая полоска) отображает на втором мониторе, при этом я в ПО не наблюдаю границ второго экрана. Не понятна логика отображения.

**Comment by MantisReligiosa** [comment]
После подключения второго монитора в ПО нужно нажать кнопку обновить на системной вкладке.

**Comment by Kim134** [comment]
Системная вкладка не работает, обновляю страницу в ручном режиме - все равно второй монитор не появляется.

**Comment by Kim134** [comment]
Границы второго монитора...

**Comment by MantisReligiosa** [comment]
Закрываю как дубликат задачи 69
