### ISSUE TITLE
Ошибка при удалении кадра

### ISSUE THREAD

**Issue by MantisReligiosa** [MantisReligiosa/Display-control#78]
При удалении в метаблоке одного кадра из двух – происходит ошибка сервера. Если метаблок пустой (не добавлено ничего –ошибки сервера нет).

**Comment by MantisReligiosa** [comment]
Добавлено начиная с версии 0.0.6 билд 87: https://dev.azure.com/mantis-religiosa/f885b45e-6407-4363-a4b4-3c2f41dda368/_apis/build/builds/87/artifacts?artifactName=Installer&fileId=CDE5ED56C064606A7F3AA59CAC79B75FDE46C67404A86C9BFD08D6C78D0A83C002&fileName=Display_control_v0.0.6_build_87.msi&api-version=5.0-preview.3

**Comment by Kim134** [comment]
не могу отловить ошибку, через раз internal server error
при удалении одного кадра в метаблоке

**Comment by MantisReligiosa** [comment]
Надеюсь в логах будут записи, надо посмотреть
