### ISSUE TITLE
Написать скрипт для вычищения базы после ошибок

### ISSUE THREAD

**Issue by MantisReligiosa** [MantisReligiosa/Display-control#95]

**Comment by Kim134** [comment]
данный скрипт будет запускаться автоматически или как? Не могу понять алгоритм работы.

**Comment by MantisReligiosa** [comment]
Этот вручную. А вообще я хочу добавить "сборщик мусора", который, скажем, раз в минуту будет подчищать базу. Но если я сделаю каскадное удаление, то этот код будет нужен только для устранения нештатных ситуаций
